### ISSUE TITLE
[Android Bootcamp] Week 1 Project: Instagram Photo Viewer

### ISSUE THREAD

**Issue by amberved** [amberved/InstagramPhotoViewer#1]
My app is complete, please review. /cc @codepathreview @codepath

**Comment by codepathreview** [comment]
:+1: nice work. A few notes after checking out the code:

* Good layout, proper view naming, usage of sp/dp, margin and relative placement rules
* Good use of string resources for text values
* Nice to see you used the SwipeRefreshLayout for easy stream refreshes
* Consider [better organizing your source files](http://guides.codepath.com/android/Organizing-your-Source-Files)
* Good job using the [ViewHolder pattern](https://github.com/codepath/android_guides/wiki/Using-an-ArrayAdapter-with-ListView#improving-performance-with-the-viewholder-pattern) to improve performance of photos `ListView`.
* Consider including a check to see if internet is available to detect any network failures. Show an approrpiate message in case of failure.
* Consider overriding `onFailure` method in `JsonHttpResponseHandler` to handle error messages appropriately.


One of the most important part of these projects is that you add additional features and tweak the UI / UX because that will provide many more learning opportunities. I would encourage you to complete the projects each week with required stories early and then spend time adding your own UI elements and experimenting with optional extensions that will improve the user experience.

We have provided a detailed [Project 1 Feedback Guide here](http://courses.codepath.com/snippets/intro_to_android/project_1_feedback) which covers the most common points we see for this project. Read through the [feedback guide point-by-point](http://courses.codepath.com/snippets/intro_to_android/project_1_feedback) to determine other ways you could improve your submission. You should consider going back and implementing applicable feedback as well. Keep in mind that one of the most important parts of Android development is learning the correct patterns and conventions.

Hopefully this first project has given you a better sense of working with RelativeLayout which is a very flexible layout system, probably one of the most powerful responsive-first layout systems available across web and mobile platforms. This assignment also gave us our first introduction to networking, working with APIs and loading remote images. The next assignment will introduce new concept such as accepting user input and navigating between activities but will also reinforce important concepts such as networking, using APIs, handling remote images.

If you have any particular questions about the assignment in general or on any of the feedback, feel free to reply here or or email us <support@codepath.com>.

**P.S.** Good to see you properly added the readme with features and screenshots to your project as described in the [submitting assignments](http://courses.codepath.com/courses/intro_to_android/pages/submitting_assignments) guide!

**Comment by amberved** [comment]
Thanks a lot on detail review message. Truly appreciate your effort and times. 

I have few questions/observations but most important of all is.  Setting size and font for each testview does not make sense. I got pained setting fonts sizes & colors in the app, but still didn't get finished product like looks.

How to get better set fonts and colors for the application? 
Can we setup something like a theme or template for the app?

**Comment by nesquena** [comment]
>  How to get better set fonts and colors for the application? Can we setup something like a theme or template for the app?

Yes, as you noticed, setting styles inline for every TextView is a lot like inline CSS on the web, very tedious. We are going to cover the solution in Week 6 but you can see our [styles and themes](http://guides.codepath.com/android/Styles-and-Themes) guide for an overview now.
